Make FileWriterWithEncoding more precisely match its JavaDoc contract
apache/commons-io pull request #295
Opened 2021-11-02 06:30 UTC by wodencafe

This pull request is to make org.apache.commons.io.output.FileWriterWithEncoding more precisely match its JavaDoc contract, for example throwing a java.lang.NullPointerException when the contract specifies that the exception will be thrown.

2021-11-02 09:19 UTC, garydgregory commented
This breaks the existing feature where the platform charset is used when null is passed in.

2021-11-02 13:59 UTC, wodencafe commented
Hi @garydgregory , if this is true then the JavaDoc should be updated instead to not suggest that a java.lang.NullPointerException is thrown when charset is null for certain method calls. Right now the class is not following the contract as specified by the JavaDoc.

2021-11-02 21:32 UTC, wodencafe commented
@garydgregory This is a fair point, I will update the PR later tonight with an approach of correcting the JavaDoc based on the existing behavior, rather than the other way around (changing the behavior to match the existing JavaDoc).

Thank you for the feedback.

2021-11-03 06:46 UTC, data443-cboyd commented
Hi @garydgregory , the pull request has been updated. Thank you.

2021-11-04 00:42 UTC, wodencafe commented
Hi @garydgregory , the pull request has been updated. Thank you.

2021-11-12 12:57 UTC, garydgregory requested changes

2022-01-30 17:19 UTC, garydgregory commented on src/main/java/org/apache/commons/io/output/FileWriterWithEncoding.java
> +                throw new IOException(ex);
Closing, no reply since November of last year.

2022-01-30 17:19 UTC, garydgregory commented
Closing, no reply since November of last year.

2022-01-30 17:19 UTC, closed without merging