Add test for AbstractByteArrayOutputStream.resetImpl and .toByteArrayImpl
apache/commons-io pull request #358
Opened 2022-05-19 12:22 UTC by lacinoire

Hey 😊
I want to contribute the following test:

Test that `baout.toString()` is equal to `""` when `reset` is called. 
This tests the methods [`AbstractByteArrayOutputStream.toByteArrayImpl`](https://github.com/apache/commons-io/blob/4aab769c3279ea63b7bcdaa163c50761bc540f8c/src/main/java/org/apache/commons/io/output/AbstractByteArrayOutputStream.java#L188) and [`AbstractByteArrayOutputStream.resetImpl`](https://github.com/apache/commons-io/blob/4aab769c3279ea63b7bcdaa163c50761bc540f8c/src/main/java/org/apache/commons/io/output/AbstractByteArrayOutputStream.java#L148). 
This test is based on the test [`copy_inputStreamToWriter`](https://github.com/apache/commons-io/blob/4aab769c3279ea63b7bcdaa163c50761bc540f8c/src/test/java/org/apache/commons/io/CopyUtilsTest.java#L83).

Curious to hear what you think!

(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))

2022-05-22 20:09 UTC, garydgregory requested changes
Thank you for your PR, see comments.

2022-05-22 20:09 UTC, garydgregory commented on src/test/java/org/apache/commons/io/output/ByteArrayOutputStreamTest.java
> +    private final byte[] inData = TestUtils.generateTestData(FILE_SIZE);
These data do not need to be tracked for all tests. Move them inside the one method that use them.

2022-05-22 20:09 UTC, garydgregory commented on src/test/java/org/apache/commons/io/output/ByteArrayOutputStreamTest.java
> +        InputStream in = new ByteArrayInputStream(inData);
Use try with resources

2022-06-03 21:28 UTC, garydgregory requested changes
@lacinoire 
Thank you for your update. Please see my scattered comments. Run a local default build (Run: `mvn`) before you push your PR as the build fails (see checkstyle error in output).

2022-06-03 21:28 UTC, garydgregory commented on src/test/java/org/apache/commons/io/output/ByteArrayOutputStreamTest.java
> +        final int file_size = (1024 * 4) + 1;
- No underscore in local variable names. 
- No need for spelling out 4097 in an expression.

2022-06-03 21:28 UTC, garydgregory commented on src/test/java/org/apache/commons/io/output/ByteArrayOutputStreamTest.java
> +                Assertions.assertEquals("", baout.toString());
No need for Assertions prefix static in a test method. Use the other methods in this file as a style guide.

2022-06-08 13:28 UTC, lacinoire commented
Thank you for the second round of comments 🙂
I addressed them and also made sure that `mvn checkstyle:check`  and `mvn verify clean` pass.
Hope the CI does to 😄

2022-06-08 16:16 UTC, garydgregory commented
That's not enough, you want to run "mvn" which will run the default goal which runs more checks.

2022-06-09 07:09 UTC, lacinoire commented
> That's not enough, you want to run "mvn" which will run the default goal which runs more checks.

Also passes ✅ 

Curious if the coverage.yml run shows any changes.

2022-06-13 12:16 UTC, lacinoire commented
Hey @garydgregory,
looked into those two tests in detail and indeed, as far as I can see they should also cover most the instructions I was targeting. Also they should covere whole new branches which i clearly not the case, trusting covdecov here.
I will go back and check why our own coverage calculation is so off in this case.

Thank you for the in-depth feedback and help with this PR! :pray: 🙂

2022-06-13 12:16 UTC, closed without merging