IO-811: Files.walk() direct and indirect callers fail to close the re…
apache/commons-io pull request #489
Opened 2023-09-30 16:57 UTC by labkey-adam

…turned Stream<Path>

2023-09-30 17:45 UTC, garydgregory requested changes
Hello @labkey-adam 
Thank you for your PR. I'll have to debug later but in the meantime, note the formatting nits.

2023-09-30 17:45 UTC, garydgregory commented on src/main/java/org/apache/commons/io/FileUtils.java
> +                    if (!ret)
Always use blocks -> { }

2023-09-30 17:45 UTC, garydgregory commented on src/main/java/org/apache/commons/io/FileUtils.java
> +            return new Iterator<File>(){
Missing space.

2023-09-30 18:51 UTC, labkey-adam commented on src/main/java/org/apache/commons/io/FileUtils.java
> +                    if (!ret)
Done

2023-09-30 18:51 UTC, labkey-adam commented on src/main/java/org/apache/commons/io/FileUtils.java
> +            return new Iterator<File>(){
Done

2023-10-01 13:05 UTC, garydgregory reviewed
Hello @labkey-adam 
Thank you for your PR. I've addressed these issues differently and credited you in `changes.xml`.

2023-10-01 13:30 UTC, garydgregory commented
Closing, see above. Jira ticket resolved.

2023-10-01 13:30 UTC, closed without merging