[IO-814] Don't throw UncheckedIOException
apache/commons-io pull request #491
Opened 2023-10-06 11:49 UTC by elharo

Fortunately the API here offered a backwards compatible fix. Since it was already declared to return null for some exceptions, this makes it return null for IOException too. This reverts the behavior breaking change without adding any API changes to anyone's code.

Also some javadoc cleanups while I was in here.

2023-10-06 12:08 UTC, garydgregory requested changes
Please don't change the style: Sentences start with a capital letter and end with a period.

2023-10-06 13:25 UTC, elharo commented
Except they aren't sentences. They're sentence fragments, and this case is explicitly called out in the [Oracle style guidelines](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#tag): "When writing the comments themselves, in general, start with a phrase and follow it with sentences if they are needed. When writing a phrase, do not capitalize and do not end with a period".

If the project wants to diverge from that, it's worth calling it out explicitly in a project specific style guide.

2023-10-06 13:32 UTC, garydgregory commented
> Except they aren't sentences. They're sentence fragments, and this case is explicitly called out in the [Oracle style guidelines](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#tag): "When writing the comments themselves, in general, start with a phrase and follow it with sentences if they are needed. When writing a phrase, do not capitalize and do not end with a period".
> 
> If the project wants to diverge from that, it's worth calling it out explicitly in a project specific style guide.

We do, under a header called "Respect The Original Style" on https://commons.apache.org/patches.html

I suppose it could go into more detail of course ;-)

2023-10-07 14:41 UTC, merged

2024-01-29 17:40 UTC, jglick commented
Would a variant of the test from #478 be useful here as a regression test? Like

```java
PathUtils.deleteFile(tempDir.resolve("nonexistent").resolve("file-does-not-exist.bin"), StandardDeleteOption.OVERRIDE_READ_ONLY));
```

which if I understand correctly should now return normally?