Add test for FileChannels.contentEquals.
apache/commons-io pull request #509
Opened 2023-11-06 19:37 UTC by smarkwal

The test in this PR uses `FileChannels.contentEquals` to compare the content of two files. Both files have the same size of 1027 bytes. While the content of file 1 starts with "ABC", the content of file 2 starts with "XYZ". Both files then contain additional identical 1024 bytes (1024 x character "x"). The two files should be considered having different content.

If `FileChannels.contentEquals` is invoked with a buffer size of 1024 bytes, it will return `true` (content is equal) instead of the expected `false` (content is different).

If calling the method with a buffer size of 1023 bytes (just 1 byte less), then the method will return the correct result `false`.

2023-11-06 20:24 UTC, garydgregory requested changes
Hello @smarkwal 
Thank you for the test. 
Would you please add the Apache license header to the new file?

2023-11-07 19:52 UTC, smarkwal commented
Hi @garydgregory 

I have added the license header and also applied a code style that seems to be used in this project. I was not able to find an `.editorconfig` file or similar. But I found [this CodeStyle wiki page](https://cwiki.apache.org/confluence/display/commons/CodeStyle) and looked at some other source files for clues.

2023-11-08 13:54 UTC, garydgregory commented
Hello @smarkwal,

Thank you for your update. Please test git master or a build from the Apache Maven snapshot repository. 

I did not merge this PR since it would fail the build; instead, I expanded the test, and committed a fix at the same time. 

You are credited in `changes.xml`.

2023-11-09 20:05 UTC, smarkwal commented
Hi @garydgregory,

Thank you very much for the quick fix and improving the test. I have been able to use 2.15.1-SNAPSHOT without problems in my project. I also did some more extensive testing and the new implementation has worked perfectly. I will close this PR.

Best,
Ste

2023-11-09 20:05 UTC, closed without merging

2023-11-09 20:36 UTC, garydgregory commented
👍